const FETCH_LEAD_REQUEST = 'FETCH_LEAD_REQUEST';
const FETCH_LEAD_SUCCESS = 'FETCH_LEAD_SUCCESS';
const FETCH_LEAD_FAILURE = 'FETCH_LEAD_FAILURE';

module.exports = {
  FETCH_LEAD_REQUEST,
  FETCH_LEAD_SUCCESS,
  FETCH_LEAD_FAILURE,
};
