const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';
const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE';

module.exports = {
  FETCH_REGISTER_REQUEST,
  FETCH_REGISTER_SUCCESS,
  FETCH_REGISTER_FAILURE,
};
